import tcmPointSearch from "../../components/tcmPointSearch";
import tcmPartSearch from "../../components/tcmPartSearch";

export default {
  components: {
    tcmPartSearch,
    tcmPointSearch,
  },
  props: {
    visible: {
      type: Boolean,
      required: false,
      default: true,
    },
    title: {
      type: String,
      required: false,
      default: "針灸穴位",
    },
    itemsTitle: {
      type: String,
      required: false,
      default: "項目",
    },
    contentHeight: {
      type: Number,
      required: false,
      default: 400,
    },
    sideWidth: {
      type: Number,
      required: false,
      default: 300,
    },
    partOptions: {
      type: Array,
      require: false,
      default: function () {
        return ["兩側", "左", "右"];
      },
    },
  },
  computed: {
    styleContentHeight() {
      return `height: ${this.contentHeight}px;`;
    },
    styleSideWidth() {
      return `width: ${this.sideWidth}px`;
    },
  },
  data() {
    return {
      curStep: "0",
      tabs: ["部位", "穴位"],
      items: new Set(),
      parts: [
        "頭",
        "頸",
        "前軀幹",
        "後軀幹",
        "背",
        "腰",
        "股",
        "左上肢",
        "左指",
        "左腕",
        "左肘",
        "左上臂",
        "左下臂",
        "左肩",
        "右上肢",
        "右指",
        "右腕",
        "右肘",
        "右上臂",
        "右下臂",
        "右肩",
        "左下肢",
        "左趾",
        "左踝",
        "左膝",
        "左大腿",
        "左小腿",
        "右下肢",
        "右趾",
        "右踝",
        "右膝",
        "右大腿",
        "右小腿",
      ],
      partsPoints: [
        {
          name: "頭頸部",
          points: [
            { name: "正營", count: 2 },
            { name: "目窗", count: 2 },
            { name: "頭臨泣", count: 2 },
            { name: "陽白", count: 2 },
            { name: "本神", count: 2 },
            { name: "完骨", count: 2 },
            { name: "頭竅陰", count: 2 },
            { name: "浮白", count: 2 },
            { name: "天衝", count: 2 },
            { name: "率谷", count: 2 },
            { name: "曲鬢", count: 2 },
            { name: "懸顱", count: 2 },
            { name: "頷厭", count: 2 },
            { name: "上關", count: 2 },
            { name: "聽會", count: 2 },
            { name: "瞳子髎", count: 2 },
            { name: "承靈", count: 2 },
            { name: "腦空", count: 2 },
            { name: "風池", count: 2 },
            { name: "肩井", count: 2 },
            { name: "睛明", count: 2 },
            { name: "攢竹", count: 2 },
            { name: "眉衝", count: 2 },
            { name: "曲差", count: 2 },
            { name: "五處", count: 2 },
            { name: "承光", count: 2 },
            { name: "通天", count: 2 },
            { name: "絡卻", count: 2 },
            { name: "玉枕", count: 2 },
            { name: "天柱", count: 2 },
            { name: "絲竹空", count: 2 },
            { name: "和髎", count: 2 },
            { name: "耳門", count: 2 },
            { name: "角孫", count: 2 },
            { name: "顱息", count: 2 },
            { name: "瘛脈", count: 2 },
            { name: "翳風", count: 2 },
            { name: "天牖", count: 2 },
            { name: "承泣", count: 2 },
            { name: "四白", count: 2 },
            { name: "巨髎", count: 2 },
            { name: "地倉", count: 2 },
            { name: "大迎", count: 2 },
            { name: "人迎", count: 2 },
            { name: "水突", count: 2 },
            { name: "頭維", count: 2 },
            { name: "下關", count: 2 },
            { name: "頰車", count: 2 },
            { name: "聽宮", count: 2 },
            { name: "顴髎", count: 2 },
            { name: "天容", count: 2 },
            { name: "天窗", count: 2 },
            { name: "迎香", count: 2 },
            { name: "禾髎", count: 2 },
            { name: "扶突", count: 2 },
            { name: "天鼎", count: 2 },
            { name: "承漿", count: 1 },
            { name: "廉泉", count: 1 },
            { name: "前頂", count: 1 },
            { name: "顖會", count: 1 },
            { name: "上星", count: 1 },
            { name: "神庭", count: 1 },
            { name: "素髎", count: 1 },
            { name: "水溝", count: 1 },
            { name: "兌端", count: 1 },
            { name: "齦交", count: 1 },
            { name: "百會", count: 1 },
            { name: "後頂", count: 1 },
            { name: "強間", count: 1 },
            { name: "腦戶", count: 1 },
            { name: "風府", count: 1 },
            { name: "啞門", count: 1 },
            { name: "大椎", count: 1 },
          ],
        },
        {
          name: "軀幹 (背面) + 臀部",
          points: [
            { name: "大杼", count: 2 },
            { name: "風門", count: 2 },
            { name: "肺俞", count: 2 },
            { name: "厥陰俞", count: 2 },
            { name: "心俞", count: 2 },
            { name: "督俞", count: 2 },
            { name: "膈俞", count: 2 },
            { name: "肝俞", count: 2 },
            { name: "膽俞", count: 2 },
            { name: "脾俞", count: 2 },
            { name: "胃俞", count: 2 },
            { name: "三焦俞", count: 2 },
            { name: "腎俞", count: 2 },
            { name: "氣海俞", count: 2 },
            { name: "大腸俞", count: 2 },
            { name: "關元俞", count: 2 },
            { name: "小腸俞", count: 2 },
            { name: "膀胱俞", count: 2 },
            { name: "中膂俞", count: 2 },
            { name: "白環俞", count: 2 },
            { name: "上髎", count: 2 },
            { name: "次髎 ", count: 2 },
            { name: "中髎 ", count: 2 },
            { name: "下髎", count: 2 },
            { name: "會陽", count: 2 },
            { name: "承扶", count: 2 },
            { name: "附分", count: 2 },
            { name: "魄戶", count: 2 },
            { name: "膏肓", count: 2 },
            { name: "神堂", count: 2 },
            { name: "譩譆", count: 2 },
            { name: "膈關", count: 2 },
            { name: "魂門", count: 2 },
            { name: "陽綱", count: 2 },
            { name: "意舍", count: 2 },
            { name: "胃倉", count: 2 },
            { name: "肓門", count: 2 },
            { name: "志室", count: 2 },
            { name: "胞肓", count: 2 },
            { name: "秩邊", count: 2 },
            { name: "大椎", count: 1 },
            { name: "陶道", count: 1 },
            { name: "身柱", count: 1 },
            { name: "神道", count: 1 },
            { name: "靈台", count: 1 },
            { name: "至陽", count: 1 },
            { name: "筋縮", count: 1 },
            { name: "中樞", count: 1 },
            { name: "脊中", count: 1 },
            { name: "懸樞", count: 1 },
            { name: "命門", count: 1 },
            { name: "腰陽關", count: 1 },
            { name: "腰俞 ", count: 1 },
            { name: "長強", count: 1 },
            { name: "肩中俞", count: 2 },
            { name: "肩外俞", count: 2 },
            { name: "曲垣", count: 2 },
            { name: "秉風", count: 2 },
            { name: "天宗", count: 2 },
            { name: "淵腋", count: 2 },
            { name: "輒筋", count: 2 },
            { name: "日月", count: 2 },
            { name: "京門 ", count: 2 },
            { name: "帶脈", count: 2 },
            { name: "五樞", count: 2 },
            { name: "維道", count: 2 },
            { name: "氣舍", count: 2 },
            { name: "缺盆", count: 2 },
            { name: "氣戶", count: 2 },
            { name: "庫房", count: 2 },
            { name: "屋翳", count: 2 },
            { name: "膺窗", count: 2 },
            { name: "乳中", count: 2 },
            { name: "乳根", count: 2 },
            { name: "不容", count: 2 },
            { name: "承滿", count: 2 },
            { name: "梁門", count: 2 },
            { name: "關門", count: 2 },
            { name: "太乙", count: 2 },
            { name: "滑肉門", count: 2 },
            { name: "天樞", count: 2 },
            { name: "外陵", count: 2 },
            { name: "大巨", count: 2 },
            { name: "水道", count: 2 },
            { name: "歸來", count: 2 },
            { name: "氣衝", count: 2 },
          ],
        },
        {
          name: "軀幹 (腹面)",
          points: [
            { name: "天突", count: 1 },
            { name: "璇璣", count: 1 },
            { name: "華蓋", count: 1 },
            { name: "紫宮", count: 1 },
            { name: "玉堂", count: 1 },
            { name: "膻中", count: 1 },
            { name: "中庭", count: 1 },
            { name: "鳩尾", count: 1 },
            { name: "巨闕", count: 1 },
            { name: "上脘", count: 1 },
            { name: "中脘", count: 1 },
            { name: "建里", count: 1 },
            { name: "下脘", count: 1 },
            { name: "水分", count: 1 },
            { name: "神闕", count: 1 },
            { name: "陰交", count: 1 },
            { name: "氣海", count: 1 },
            { name: "石門", count: 1 },
            { name: "關元", count: 1 },
            { name: "中極", count: 1 },
            { name: "曲骨", count: 1 },
            { name: "大包", count: 2 },
            { name: "周榮", count: 2 },
            { name: "胸鄉", count: 2 },
            { name: "天谿", count: 2 },
            { name: "食竇", count: 2 },
            { name: "腹哀", count: 2 },
            { name: "大橫", count: 2 },
            { name: "腹結", count: 2 },
            { name: "府舍", count: 2 },
            { name: "沖門", count: 2 },
            { name: "期門", count: 2 },
            { name: "章門", count: 2 },
            { name: "急脈", count: 2 },
            { name: "陰廉", count: 2 },
            { name: "俞府", count: 2 },
            { name: "彧中", count: 2 },
            { name: "神藏", count: 2 },
            { name: "靈墟", count: 2 },
            { name: "神封", count: 2 },
            { name: "步廊", count: 2 },
            { name: "幽門", count: 2 },
            { name: "腹通谷", count: 2 },
            { name: "陰都", count: 2 },
            { name: "石關", count: 2 },
            { name: "商曲", count: 2 },
            { name: "肓俞", count: 2 },
            { name: "中注", count: 2 },
            { name: "四滿", count: 2 },
            { name: "氣穴", count: 2 },
            { name: "大赫", count: 2 },
            { name: "橫骨", count: 2 },
            { name: "天髎", count: 2 },
            { name: "天池", count: 2 },
            { name: "天泉", count: 2 },
          ],
        },
        {
          name: "上肢 + 手部 (陽面)",
          points: [
            { name: "肩髎", count: 2 },
            { name: "臑會", count: 2 },
            { name: "消濼", count: 2 },
            { name: "清冷淵 ", count: 2 },
            { name: "天井", count: 2 },
            { name: "四瀆", count: 2 },
            { name: "三陽絡", count: 2 },
            { name: "會宗", count: 2 },
            { name: "支溝", count: 2 },
            { name: "外關", count: 2 },
            { name: "陽池", count: 2 },
            { name: "中渚", count: 2 },
            { name: "液門", count: 2 },
            { name: "關衝", count: 2 },
            { name: "臑俞", count: 2 },
            { name: "肩貞", count: 2 },
            { name: "小海 ", count: 2 },
            { name: "支正", count: 2 },
            { name: "養老", count: 2 },
            { name: "陽谷", count: 2 },
            { name: "腕骨", count: 2 },
            { name: "後谿", count: 2 },
            { name: "前谷", count: 2 },
            { name: "少澤", count: 2 },
            { name: "巨骨", count: 2 },
            { name: "肩髃", count: 2 },
            { name: "臂臑 ", count: 2 },
            { name: "手五里", count: 2 },
            { name: "肘髎", count: 2 },
            { name: "曲池", count: 2 },
            { name: "手三里", count: 2 },
            { name: "上廉", count: 2 },
            { name: "下廉", count: 2 },
            { name: "溫溜", count: 2 },
            { name: "篇歷", count: 2 },
            { name: "陽谿", count: 2 },
            { name: "合谷", count: 2 },
            { name: "三間", count: 2 },
            { name: "二間", count: 2 },
            { name: "商陽", count: 2 },
          ],
        },
        {
          name: "上肢 + 手部 (陰面)",
          points: [
            { name: "中府", count: 2 },
            { name: "雲門", count: 2 },
            { name: "天府", count: 2 },
            { name: "俠白", count: 2 },
            { name: "尺澤", count: 2 },
            { name: "孔最", count: 2 },
            { name: "列缺", count: 2 },
            { name: "經渠", count: 2 },
            { name: "太淵", count: 2 },
            { name: "魚際", count: 2 },
            { name: "少商", count: 2 },
            { name: "極泉", count: 2 },
            { name: "青靈", count: 2 },
            { name: "少海", count: 2 },
            { name: "靈道", count: 2 },
            { name: "通里", count: 2 },
            { name: "陰郄", count: 2 },
            { name: "神門", count: 2 },
            { name: "少府", count: 2 },
            { name: "少衝", count: 2 },
            { name: "天池", count: 2 },
            { name: "天泉", count: 2 },
            { name: "曲澤", count: 2 },
            { name: "郄門", count: 2 },
            { name: "間使", count: 2 },
            { name: "內關", count: 2 },
            { name: "大陵", count: 2 },
            { name: "勞宮", count: 2 },
            { name: "中衝", count: 2 },
          ],
        },
        {
          name: "下肢 + 腿部 (陽面)",
          points: [
            { name: "承扶", count: 2 },
            { name: "殷門", count: 2 },
            { name: "浮郄", count: 2 },
            { name: "委陽", count: 2 },
            { name: "委中", count: 2 },
            { name: "合陽", count: 2 },
            { name: "承筋", count: 2 },
            { name: "承山", count: 2 },
            { name: "飛揚", count: 2 },
            { name: "跗陽", count: 2 },
            { name: "崑崙", count: 2 },
            { name: "僕參", count: 2 },
            { name: "申脈", count: 2 },
            { name: "金門", count: 2 },
            { name: "京骨", count: 2 },
            { name: "束骨", count: 2 },
            { name: "足通骨", count: 2 },
            { name: "至陰", count: 2 },
            { name: "居髎", count: 2 },
            { name: "環跳", count: 2 },
            { name: "風市", count: 2 },
            { name: "中瀆", count: 2 },
            { name: "膝陽關", count: 2 },
            { name: "陽陵泉", count: 2 },
            { name: "陽交", count: 2 },
            { name: "外丘", count: 2 },
            { name: "光明", count: 2 },
            { name: "陽輔", count: 2 },
            { name: "懸鍾", count: 2 },
            { name: "丘墟", count: 2 },
            { name: "足臨泣", count: 2 },
            { name: "地五會", count: 2 },
            { name: "俠谿", count: 2 },
            { name: "足竅陰", count: 2 },
            { name: "髀關", count: 2 },
            { name: "伏兔", count: 2 },
            { name: "陰市", count: 2 },
            { name: "梁丘", count: 2 },
            { name: "犢鼻", count: 2 },
            { name: "足三里", count: 2 },
            { name: "上巨虛", count: 2 },
            { name: "條口", count: 2 },
            { name: "下巨虛", count: 2 },
            { name: "豐隆", count: 2 },
            { name: "解谿", count: 2 },
            { name: "衝陽", count: 2 },
            { name: "陷谷", count: 2 },
            { name: "內庭", count: 2 },
            { name: "厲兌", count: 2 },
          ],
        },
        {
          name: "下肢 + 腿部 (陰面)",
          points: [
            { name: "箕門 ", count: 2 },
            { name: "血海", count: 2 },
            { name: "陰陵泉", count: 2 },
            { name: "地機", count: 2 },
            { name: "漏谷", count: 2 },
            { name: "三陰交", count: 2 },
            { name: "商丘", count: 2 },
            { name: "公孫", count: 2 },
            { name: "太白", count: 2 },
            { name: "大都", count: 2 },
            { name: "隱白", count: 2 },
            { name: "足五里 ", count: 2 },
            { name: "陰包", count: 2 },
            { name: "曲泉", count: 2 },
            { name: "膝關", count: 2 },
            { name: "中都", count: 2 },
            { name: "蠡溝", count: 2 },
            { name: "中封", count: 2 },
            { name: "太衝", count: 2 },
            { name: "行間", count: 2 },
            { name: "大敦", count: 2 },
            { name: "陰谷 ", count: 2 },
            { name: "築賓", count: 2 },
            { name: "交信", count: 2 },
            { name: "復溜", count: 2 },
            { name: "照海", count: 2 },
            { name: "水泉", count: 2 },
            { name: "大鐘", count: 2 },
            { name: "太谿", count: 2 },
            { name: "然谷", count: 2 },
            { name: "湧泉", count: 2 },
            { name: "會陰 ", count: 1 },
          ],
        },
      ],
      meridian: [
        {
          name: "手太陰肺經",
          points: [
            { name: "中府", count: 2 },
            { name: "雲門", count: 2 },
            { name: "天府", count: 2 },
            { name: "俠白", count: 2 },
            { name: "尺澤", count: 2 },
            { name: "孔最", count: 2 },
            { name: "列缺", count: 2 },
            { name: "經渠", count: 2 },
            { name: "太淵", count: 2 },
            { name: "魚際", count: 2 },
            { name: "少商", count: 2 },
          ],
        },
        {
          name: "手厥陰心包經",
          points: [
            { name: "天池", count: 2 },
            { name: "天泉", count: 2 },
            { name: "曲澤", count: 2 },
            { name: "郄門", count: 2 },
            { name: "間使", count: 2 },
            { name: "內關", count: 2 },
            { name: "大陵", count: 2 },
            { name: "勞宮", count: 2 },
            { name: "中衝", count: 2 },
          ],
        },
        {
          name: "手少陰心經",
          points: [
            { name: "極泉", count: 2 },
            { name: "青靈", count: 2 },
            { name: "少海", count: 2 },
            { name: "靈道", count: 2 },
            { name: "通里", count: 2 },
            { name: "陰郄", count: 2 },
            { name: "神門", count: 2 },
            { name: "少府", count: 2 },
            { name: "少衝", count: 2 },
          ],
        },
        {
          name: "手陽明大腸經",
          points: [
            { name: "巨骨", count: 2 },
            { name: "肩髃", count: 2 },
            { name: "臂臑 ", count: 2 },
            { name: "手五里", count: 2 },
            { name: "肘髎", count: 2 },
            { name: "曲池", count: 2 },
            { name: "手三里", count: 2 },
            { name: "上廉", count: 2 },
            { name: "下廉", count: 2 },
            { name: "溫溜", count: 2 },
            { name: "篇歷", count: 2 },
            { name: "陽谿", count: 2 },
            { name: "合谷", count: 2 },
            { name: "三間", count: 2 },
            { name: "二間", count: 2 },
            { name: "商陽", count: 2 },
          ],
        },
        {
          name: "手少陽三焦經",
          points: [
            { name: "肩髎", count: 2 },
            { name: "臑會", count: 2 },
            { name: "消濼", count: 2 },
            { name: "清冷淵 ", count: 2 },
            { name: "天井", count: 2 },
            { name: "四瀆", count: 2 },
            { name: "三陽絡", count: 2 },
            { name: "會宗", count: 2 },
            { name: "支溝", count: 2 },
            { name: "外關", count: 2 },
            { name: "陽池", count: 2 },
            { name: "中渚", count: 2 },
            { name: "液門", count: 2 },
            { name: "關衝", count: 2 },
            { name: "絲竹空", count: 2 },
            { name: "和髎", count: 2 },
            { name: "耳門", count: 2 },
            { name: "角孫", count: 2 },
            { name: "顱息", count: 2 },
            { name: "瘛脈", count: 2 },
            { name: "翳風", count: 2 },
            { name: "天牖", count: 2 },
          ],
        },
        {
          name: "手太陽小腸經",
          points: [
            { name: "臑俞", count: 2 },
            { name: "肩貞", count: 2 },
            { name: "小海 ", count: 2 },
            { name: "支正", count: 2 },
            { name: "養老", count: 2 },
            { name: "陽谷", count: 2 },
            { name: "腕骨", count: 2 },
            { name: "後谿", count: 2 },
            { name: "前谷", count: 2 },
            { name: "少澤", count: 2 },
          ],
        },
        {
          name: "足陽明胃經",
          points: [
            { name: "髀關", count: 2 },
            { name: "伏兔", count: 2 },
            { name: "陰市", count: 2 },
            { name: "梁丘", count: 2 },
            { name: "犢鼻", count: 2 },
            { name: "足三里", count: 2 },
            { name: "上巨虛", count: 2 },
            { name: "條口", count: 2 },
            { name: "下巨虛", count: 2 },
            { name: "豐隆", count: 2 },
            { name: "解谿", count: 2 },
            { name: "衝陽", count: 2 },
            { name: "陷谷", count: 2 },
            { name: "內庭", count: 2 },
            { name: "厲兌", count: 2 },
          ],
        },
        {
          name: "足少陽膽經",
          points: [
            { name: "居髎", count: 2 },
            { name: "環跳", count: 2 },
            { name: "風市", count: 2 },
            { name: "中瀆", count: 2 },
            { name: "膝陽關", count: 2 },
            { name: "陽陵泉", count: 2 },
            { name: "陽交", count: 2 },
            { name: "外丘", count: 2 },
            { name: "光明", count: 2 },
            { name: "陽輔", count: 2 },
            { name: "懸鍾", count: 2 },
            { name: "丘墟", count: 2 },
            { name: "足臨泣", count: 2 },
            { name: "地五會", count: 2 },
            { name: "俠谿", count: 2 },
            { name: "足竅陰", count: 2 },
          ],
        },
        {
          name: "足太陽膀胱經",
          points: [
            { name: "大杼", count: 2 },
            { name: "風門", count: 2 },
            { name: "肺俞", count: 2 },
            { name: "厥陰俞", count: 2 },
            { name: "心俞", count: 2 },
            { name: "督俞", count: 2 },
            { name: "膈俞", count: 2 },
            { name: "肝俞", count: 2 },
            { name: "膽俞", count: 2 },
            { name: "脾俞", count: 2 },
            { name: "胃俞", count: 2 },
            { name: "三焦俞", count: 2 },
            { name: "腎俞", count: 2 },
            { name: "氣海俞", count: 2 },
            { name: "大腸俞", count: 2 },
            { name: "關元俞", count: 2 },
            { name: "小腸俞", count: 2 },
            { name: "膀胱俞", count: 2 },
            { name: "中膂俞", count: 2 },
            { name: "白環俞", count: 2 },
            { name: "上髎", count: 2 },
            { name: "次髎 ", count: 2 },
            { name: "中髎 ", count: 2 },
            { name: "下髎", count: 2 },
            { name: "會陽", count: 2 },
            { name: "承扶", count: 2 },
            { name: "附分", count: 2 },
            { name: "魄戶", count: 2 },
            { name: "膏肓", count: 2 },
            { name: "神堂", count: 2 },
            { name: "譩譆", count: 2 },
            { name: "膈關", count: 2 },
            { name: "魂門", count: 2 },
            { name: "陽綱", count: 2 },
            { name: "意舍", count: 2 },
            { name: "胃倉", count: 2 },
            { name: "肓門", count: 2 },
            { name: "志室", count: 2 },
            { name: "胞肓", count: 2 },
            { name: "秩邊", count: 2 },
          ],
        },
        {
          name: "足太陰脾經",
          points: [
            { name: "箕門 ", count: 2 },
            { name: "血海", count: 2 },
            { name: "陰陵泉", count: 2 },
            { name: "地機", count: 2 },
            { name: "漏谷", count: 2 },
            { name: "三陰交", count: 2 },
            { name: "商丘", count: 2 },
            { name: "公孫", count: 2 },
            { name: "太白", count: 2 },
            { name: "大都", count: 2 },
            { name: "隱白", count: 2 },
          ],
        },
        {
          name: "足厥陰肝經",
          points: [
            { name: "足五里 ", count: 2 },
            { name: "陰包", count: 2 },
            { name: "曲泉", count: 2 },
            { name: "膝關", count: 2 },
            { name: "中都", count: 2 },
            { name: "蠡溝", count: 2 },
            { name: "中封", count: 2 },
            { name: "太衝", count: 2 },
            { name: "行間", count: 2 },
            { name: "大敦", count: 2 },
          ],
        },
        {
          name: "足少陰腎經",
          points: [
            { name: "俞府", count: 2 },
            { name: "彧中", count: 2 },
            { name: "神藏", count: 2 },
            { name: "靈墟", count: 2 },
            { name: "神封", count: 2 },
            { name: "步廊", count: 2 },
            { name: "幽門", count: 2 },
            { name: "腹通谷", count: 2 },
            { name: "陰都", count: 2 },
            { name: "石關", count: 2 },
            { name: "商曲", count: 2 },
            { name: "肓俞", count: 2 },
            { name: "中注", count: 2 },
            { name: "四滿", count: 2 },
            { name: "氣穴", count: 2 },
            { name: "大赫", count: 2 },
            { name: "橫骨", count: 2 },
          ],
        },
        {
          name: "任脈",
          points: [
            { name: "承漿", count: 1 },
            { name: "廉泉", count: 1 },
            { name: "天突", count: 1 },
            { name: "璇璣", count: 1 },
            { name: "華蓋", count: 1 },
            { name: "紫宮", count: 1 },
            { name: "玉堂", count: 1 },
            { name: "膻中", count: 1 },
            { name: "中庭", count: 1 },
            { name: "鳩尾", count: 1 },
            { name: "巨闕", count: 1 },
            { name: "上脘", count: 1 },
            { name: "中脘", count: 1 },
            { name: "建里", count: 1 },
            { name: "下脘", count: 1 },
            { name: "水分", count: 1 },
            { name: "神闕", count: 1 },
            { name: "陰交", count: 1 },
            { name: "氣海", count: 1 },
            { name: "石門", count: 1 },
            { name: "關元", count: 1 },
            { name: "中極", count: 1 },
            { name: "曲骨", count: 1 },
          ],
        },
        {
          name: "督脈",
          points: [
            { name: "前頂", count: 1 },
            { name: "顖會", count: 1 },
            { name: "上星", count: 1 },
            { name: "神庭", count: 1 },
            { name: "素髎", count: 1 },
            { name: "水溝", count: 1 },
            { name: "兌端", count: 1 },
            { name: "齦交", count: 1 },
            { name: "百會", count: 1 },
            { name: "後頂", count: 1 },
            { name: "強間", count: 1 },
            { name: "腦戶", count: 1 },
            { name: "風府", count: 1 },
            { name: "啞門", count: 1 },
            { name: "大椎", count: 1 },
            { name: "大椎", count: 1 },
            { name: "陶道", count: 1 },
            { name: "身柱", count: 1 },
            { name: "神道", count: 1 },
            { name: "靈台", count: 1 },
            { name: "至陽", count: 1 },
            { name: "筋縮", count: 1 },
            { name: "中樞", count: 1 },
            { name: "脊中", count: 1 },
            { name: "懸樞", count: 1 },
            { name: "命門", count: 1 },
            { name: "腰陽關", count: 1 },
            { name: "腰俞 ", count: 1 },
            { name: "長強", count: 1 },
          ],
        },
      ],
    };
  },
  methods: {
    goBack() {
      this.$emit("goBack");
    },
    handleCancel() {
      this.handleCleanCart();
      this.goBack();
    },
    handleClickConfirm() {
      this.goBack();
    },
    handleAddItem(item) {
      this.items.add(item);
      this.$forceUpdate();
    },
    handleAddPointItem(item) {
      if (item.count >= 2) {
        item.option = this.partOptions[0];
      }
      this.items.add(item);
      this.$forceUpdate();
    },
    handleRemoveItem(item) {
      this.items.delete(item);
      this.$forceUpdate();
    },
    handleCleanCart(item) {
      this.items.clear();
      this.$forceUpdate();
    },
    handleItemOptionChange() {
      this.$forceUpdate();
    },
  },
};
